In [3]:
import cv2
from scipy import signal
import numpy as np

video=cv2.VideoCapture(0)
while True:
    check,frame=video.read()
    x = video.get(3)
    y = video.get(4)
    cv2.rectangle(frame,(int(x/3),int(y/3)),(int(2*x/3),int(2*y/3)),(0,255,0),3)     
    cv2.imshow("image",frame)
    key=cv2.waitKey(1)
    if key == ord('q'):
        print(frame)
        break
    if key == ord('w'):
        hand=frame[int(y/3):int(2*y/3),int(x/3):int(2*x/3)]
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        cv2.imshow("image1",hsv)
video.release()




cv2.destroyAllWindows()
    

[[[  4   9  53]
  [  4   9  53]
  [  0   7  48]
  ...
  [134 127 143]
  [122 124 139]
  [124 126 141]]

 [[  0   8  51]
  [  0   8  51]
  [  1   7  49]
  ...
  [128 124 147]
  [118 128 144]
  [116 126 142]]

 [[  2  10  47]
  [  1   9  46]
  [  1   7  49]
  ...
  [126 129 141]
  [113 130 140]
  [113 130 140]]

 ...

 [[  0  15  24]
  [  0  17  26]
  [  0  17  24]
  ...
  [255 186 107]
  [255 185 114]
  [255 186 115]]

 [[  0  17  26]
  [  0  17  26]
  [  0  16  26]
  ...
  [255 186 104]
  [255 183 110]
  [255 186 113]]

 [[  0  17  27]
  [  0  16  26]
  [  0  17  26]
  ...
  [255 188 101]
  [255 187 108]
  [255 189 110]]]
